cmake_minimum_required(VERSION 3.25)

# Exercise discovery without depending on which compilers the host has installed.
if(NOT DEFINED CASE)
    foreach(case IN ITEMS prefer_clang gcc_fallback missing explicit environment toolchain parent_cxx
            clang gnu appleclang msvc mixed_msvc clang_cl visual_studio)
        execute_process(
            COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" "-DTEST_ROOT=${TEST_ROOT}"
                -P "${CMAKE_CURRENT_LIST_FILE}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(case MATCHES "^(missing|msvc|mixed_msvc|clang_cl|visual_studio)$")
            if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "GxBuild3 requires")
                message(FATAL_ERROR "${case}: expected compiler rejection\n${output}${error}")
            endif()
        elseif(NOT result EQUAL 0)
            message(FATAL_ERROR "${case}: ${output}${error}")
        endif()
        message(STATUS "${case}: passed")
    endforeach()
    return()
endif()

if(NOT TEST_ROOT)
    message(FATAL_ERROR "Pass -DTEST_ROOT=<temporary build directory>")
endif()
set(case_dir "${TEST_ROOT}/${CASE}")
file(MAKE_DIRECTORY "${case_dir}/gcc" "${case_dir}/clang")
set(ENV{CC} "")
set(ENV{CXX} "")
set(ENV{CMAKE_TOOLCHAIN_FILE} "")
set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH FALSE)
set(CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH FALSE)
set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH FALSE)
set(CMAKE_FIND_USE_INSTALL_PREFIX FALSE)
set(CMAKE_PROGRAM_PATH "${case_dir}/gcc;${case_dir}/clang")
set(CMAKE_GENERATOR Ninja)

function(compiler_stub directory name)
    if(CMAKE_HOST_WIN32)
        string(APPEND name ".exe")
    endif()
    file(WRITE "${case_dir}/${directory}/${name}" "")
    file(CHMOD "${case_dir}/${directory}/${name}"
        PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endfunction()

if(CASE STREQUAL "prefer_clang" OR CASE STREQUAL "gcc_fallback")
    compiler_stub(gcc gcc)
    compiler_stub(gcc g++)
endif()
if(CASE STREQUAL "prefer_clang")
    compiler_stub(clang clang)
    compiler_stub(clang clang++)
elseif(CASE STREQUAL "explicit")
    set(CMAKE_C_COMPILER "/custom/gcc")
    set(CMAKE_CXX_COMPILER "/custom/g++")
elseif(CASE STREQUAL "environment")
    set(ENV{CC} "/custom/gcc")
    set(ENV{CXX} "/custom/g++")
elseif(CASE STREQUAL "toolchain")
    set(CMAKE_TOOLCHAIN_FILE "/custom/toolchain.cmake")
elseif(CASE STREQUAL "parent_cxx")
    set(CMAKE_CXX_COMPILER "/custom/g++")
    set(CMAKE_CXX_COMPILER_LOADED TRUE)
elseif(CASE STREQUAL "visual_studio")
    set(CMAKE_GENERATOR "Visual Studio 17 2022")
elseif(CASE MATCHES "^(clang|gnu|appleclang|msvc|mixed_msvc|clang_cl)$")
    # Validation uses the IDs CMake reports after project() enables both languages.
    set(CMAKE_C_COMPILER "/custom/cc")
    set(CMAKE_CXX_COMPILER "/custom/c++")
    set(CMAKE_C_COMPILER_ID Clang)
    set(CMAKE_CXX_COMPILER_ID Clang)
    if(CASE STREQUAL "gnu")
        set(CMAKE_C_COMPILER_ID GNU)
        set(CMAKE_CXX_COMPILER_ID GNU)
    elseif(CASE STREQUAL "appleclang")
        set(CMAKE_C_COMPILER_ID AppleClang)
        set(CMAKE_CXX_COMPILER_ID AppleClang)
    elseif(CASE STREQUAL "msvc")
        set(CMAKE_CXX_COMPILER_ID MSVC)
    elseif(CASE STREQUAL "mixed_msvc")
        set(CMAKE_C_COMPILER_ID MSVC)
    elseif(CASE STREQUAL "clang_cl")
        set(CMAKE_CXX_COMPILER_FRONTEND_VARIANT MSVC)
    endif()
endif()

include("${CMAKE_CURRENT_LIST_DIR}/../cmake/SelectCompilers.cmake")
if(DEFINED CMAKE_C_COMPILER_ID)
    gxbuild3_validate_compilers()
endif()

if(CASE STREQUAL "prefer_clang")
    if(NOT CMAKE_C_COMPILER MATCHES "/clang/clang(\\.exe)?$"
            OR NOT CMAKE_CXX_COMPILER MATCHES "/clang/clang\\+\\+(\\.exe)?$")
        message(FATAL_ERROR "Clang must win even when GCC appears earlier in the search path")
    endif()
elseif(CASE STREQUAL "gcc_fallback")
    if(NOT CMAKE_C_COMPILER MATCHES "/gcc/gcc(\\.exe)?$"
            OR NOT CMAKE_CXX_COMPILER MATCHES "/gcc/g\\+\\+(\\.exe)?$")
        message(FATAL_ERROR "GCC must be selected when Clang is absent")
    endif()
elseif(CASE STREQUAL "explicit")
    if(NOT CMAKE_C_COMPILER STREQUAL "/custom/gcc" OR NOT CMAKE_CXX_COMPILER STREQUAL "/custom/g++")
        message(FATAL_ERROR "Explicit compiler choices must be preserved")
    endif()
elseif(CASE STREQUAL "environment" OR CASE STREQUAL "toolchain")
    if(DEFINED CMAKE_C_COMPILER OR DEFINED CMAKE_CXX_COMPILER)
        message(FATAL_ERROR "Do not preempt environment or toolchain compiler choices")
    endif()
elseif(CASE STREQUAL "parent_cxx")
    if(DEFINED CMAKE_C_COMPILER OR NOT CMAKE_CXX_COMPILER STREQUAL "/custom/g++")
        message(FATAL_ERROR "Let CMake infer C from the parent's enabled C++ toolchain")
    endif()
endif()
