cmake_minimum_required(VERSION 3.29)

# Coverage-ledger guard (migration only; deleted with tests/migration/). Every old test function,
# static_assert, table row and main-only check has a row in tests/migration/ledger/<OldFile>.tsv
# (seeded by SeedLedger.cmake):
#
#   id  old_symbol@line  old_assert_sites  new_test  status[;note:<text>]
#
# status is pending, ported, new, merged:<target>, static_assert@<file>:<line> or
# retired:<reason>; any status may carry `;note:<text>`. new_test is the ctest entry that runs the
# case: `<prefix>.<Suite>.<Test>` (or `<prefix>.<Inst>/<Suite>.<Test>/<Row>`) when the case is
# its own entry, `<prefix>.<bundle>#<label>` when it runs inside a BUNDLE entry (label is the case
# minus `<bundle>.`, or the whole case for an instantiation picked up by a Suite bundle).
#
# old_symbol is a test_* function, `static_assert#<sha1-10>` (the statement without whitespace),
# a PIN_SIZE/PIN_FIELD invocation, or for hand rows any identifier of the old file, optionally
# with a `#<row label>`: such a row is checked against the identifier before the '#'.
#
# The guard fails when
#   (a) a ported or new row's new_test is not the entry of a case some binary lists (a stale
#       '#' label or a wrong bundle name fails here too);
#   (b) a pending row's old file is gone or its symbol is gone from it, so a port and the
#       deletion of the old code land in one commit;
#   (c) a ported, merged, retired or static_assert@ row's old symbol is still in its old file
#       (not checked for '#'-labelled hand rows, whose enclosing symbol may outlive one row);
#   (d) a static_assert@<file>:<line> does not point at a static_assert or PIN_* line;
#   (e) a merged:<target> names neither a ported/new row id nor a listed entry;
#   (f) two ported/new rows claim one new_test;
#   (g) the EXPECT_/ASSERT_/matches_golden count in the new TEST body is below
#       ceil(old_assert_sites / 2) and the row carries no note;
#   (h) a ledger's automatic or hand row count (excluding status new) differs from its header;
#   (i) a test_ function, static_assert or PIN_* invocation still in an old file has no row;
# and, once ported, when core/WireLayoutPins.cpp holds fewer than 46 static_asserts or the
# listing lacks the 32 Row/StfsErrorCode rows plus the 1 NeedsDevFull/StfsErrorCode row.
# It prints `ledger: ported N, merged M, retired R, static K, new X, pending P`.
#
# Inputs (-D): SOURCE_ROOT, GTEST_BINARIES (registry file), LEDGER_DIR (defaults to
# tests/migration/ledger; a scratch copy for a mutation check).

foreach(input SOURCE_ROOT GTEST_BINARIES)
    if(NOT DEFINED ${input})
        message(FATAL_ERROR "CoverageLedger: ${input} is required")
    endif()
endforeach()
if(NOT DEFINED LEDGER_DIR)
    set(LEDGER_DIR "${SOURCE_ROOT}/tests/migration/ledger")
endif()
include(${CMAKE_CURRENT_LIST_DIR}/LedgerCommon.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/GtestListing.cmake)

set(problems "")
macro(problem text)
    list(APPEND problems "${text}")
endmacro()

# ---- Listed cases, keyed by their new_test spelling and by entry name -------------------------
gxbuild3_gtest_load("${GTEST_BINARIES}")
foreach(bin IN LISTS GTEST_BINARIES)
    set(prefix "${GTEST_${bin}_PREFIX}")
    foreach(bundle IN LISTS GTEST_${bin}_BUNDLES)
        gxbuild3_gtest_key(key "${prefix}.${bundle}")
        set(entry_${key} TRUE)
    endforeach()
    foreach(case IN LISTS GTEST_${bin}_CASES)
        gxbuild3_gtest_new_test(spelling "${prefix}" "${GTEST_${bin}_BUNDLES}" "${case}")
        gxbuild3_gtest_key(key "${spelling}")
        set(case_of_${key} "${case}")
        set(entry_${key} TRUE)
        gxbuild3_gtest_key(key "${prefix}.${case}")
        set(spelling_of_${key} "${spelling}")
    endforeach()
endforeach()

# ---- Ledger rows ------------------------------------------------------------------------------
file(GLOB ledgers "${LEDGER_DIR}/*.tsv")
list(SORT ledgers)
if(NOT ledgers)
    message(FATAL_ERROR "CoverageLedger: no ledger in ${LEDGER_DIR}")
endif()
set(row_ids "")
set(ledger_olds "")
foreach(ledger IN LISTS ledgers)
    get_filename_component(ledger_name "${ledger}" NAME)
    gxbuild3_ledger_read_lines("${ledger}" lines)
    list(GET lines 0 header)
    if(NOT header MATCHES "^# Coverage ledger for ([^ ]+) ")
        problem("${ledger_name}: the first line must name the old file")
        continue()
    endif()
    set(old "${CMAKE_MATCH_1}")
    list(APPEND ledger_olds "${old}")
    set(ledger_name_${old} "${ledger_name}")
    set(ledger_symbols_${old} "")
    list(GET lines 1 counts)
    if(NOT counts MATCHES "^# rows: ([0-9]+) automatic, ([0-9]+) hand\\.")
        problem("${ledger_name}: the second line must state `# rows: <n> automatic, <n> hand.`")
        continue()
    endif()
    set(expected_automatic ${CMAKE_MATCH_1})
    set(expected_hand ${CMAKE_MATCH_2})
    set(section automatic)
    set(counted_automatic 0)
    set(counted_hand 0)
    set(number 0)
    foreach(line IN LISTS lines)
        math(EXPR number "${number} + 1")
        if(line STREQUAL "# hand")
            set(section hand)
            continue()
        endif()
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        if(NOT line MATCHES "\tnew(@SC@note:[^\t]*)?$")
            math(EXPR counted_${section} "${counted_${section}} + 1")
        endif()
        string(REPLACE "\t" ";" fields "${line}")
        list(LENGTH fields count)
        if(NOT count EQUAL 5)
            problem("${ledger_name}:${number}: ${count} fields, expected 5 tab-separated fields")
            continue()
        endif()
        list(GET fields 0 id)
        list(GET fields 1 symbol)
        list(GET fields 2 sites)
        list(GET fields 3 new_test)
        list(GET fields 4 status)
        if(DEFINED row_old_${id})
            problem("${ledger_name}:${number}: duplicate row id ${id}")
            continue()
        endif()
        if(NOT symbol MATCHES "^(.+)@([0-9]+)$")
            problem("${ledger_name}:${number}: old_symbol must be <symbol>@<line>")
            continue()
        endif()
        if(NOT sites MATCHES "^([0-9]+|-)$")
            problem("${ledger_name}:${number}: old_assert_sites must be a count or -")
            continue()
        endif()
        set(note FALSE)
        if(status MATCHES "^(.*)@SC@note:.+$")
            set(status "${CMAKE_MATCH_1}")
            set(note TRUE)
        endif()
        if(NOT status MATCHES
           "^(pending|ported|new|merged:[^@]+|retired:.+|static_assert@[^:]+:[0-9]+)$")
            problem("${ledger_name}:${number}: unknown status ${status}")
            continue()
        endif()
        list(APPEND row_ids "${id}")
        set(row_where_${id} "${ledger_name}:${number}")
        set(row_old_${id} "${old}")
        string(REGEX REPLACE "@[0-9]+$" "" row_symbol_${id} "${symbol}")
        set(row_sites_${id} "${sites}")
        set(row_new_${id} "${new_test}")
        set(row_status_${id} "${status}")
        set(row_note_${id} ${note})
        list(APPEND ledger_symbols_${old} "${row_symbol_${id}}")
    endforeach()
    # (h) a row was lost: port commits change statuses, they never delete rows.
    if(NOT counted_automatic EQUAL expected_automatic OR NOT counted_hand EQUAL expected_hand)
        problem("${ledger_name}: ${counted_automatic} automatic and ${counted_hand} hand rows, the header states ${expected_automatic} and ${expected_hand}: a row was lost or added without status new (rule h)")
    endif()
endforeach()

# ---- Old sources: what is still there ---------------------------------------------------------
# Scanned once per old file that still exists: its test_ functions, static_assert fingerprints,
# PIN invocations and whitespace-free text.
set(scanned_files "")
macro(scan_old old)
    if(NOT "${old}" IN_LIST scanned_files)
        list(APPEND scanned_files "${old}")
        set(old_exists_${old} FALSE)
        if(EXISTS "${SOURCE_ROOT}/${old}")
            set(old_exists_${old} TRUE)
            file(READ "${SOURCE_ROOT}/${old}" _text)
            string(REGEX REPLACE "[ \t\r\n]" "" old_flat_${old} "${_text}")
            set(old_text_${old} "${_text}")
            set(old_functions_${old} "")
            set(old_statics_${old} "")
            set(old_pins_${old} "")
            if("${old}" MATCHES "\\.cpp$")
                gxbuild3_ledger_scan_source("${SOURCE_ROOT}/${old}")
                set(old_functions_${old} "${LEDGER_FUNCTIONS}")
                foreach(_entry IN LISTS LEDGER_STATIC_ASSERTS)
                    string(REGEX REPLACE "^[0-9]+\\|" "" _digest "${_entry}")
                    list(APPEND old_statics_${old} "${_digest}")
                endforeach()
                set(old_pins_${old} "")
                foreach(_entry IN LISTS LEDGER_PINS)
                    string(REGEX REPLACE "^[0-9]+\\|" "" _pin "${_entry}")
                    list(APPEND old_pins_${old} "${_pin}")
                endforeach()
            endif()
        endif()
    endif()
endmacro()

# symbol_present(<out> <old> <symbol>)
macro(symbol_present out old symbol)
    scan_old("${old}")
    set(${out} FALSE)
    if(old_exists_${old})
        set(_symbol "${symbol}")
        string(REGEX REPLACE "#.*$" "" _base "${_symbol}")
        if(_symbol MATCHES "^static_assert#([0-9a-f]+)$")
            if(CMAKE_MATCH_1 IN_LIST old_statics_${old})
                set(${out} TRUE)
            endif()
        elseif(_base MATCHES "^test_[A-Za-z0-9_]+$")
            if(_base IN_LIST old_functions_${old})
                set(${out} TRUE)
            endif()
        elseif(_base MATCHES "\\(")
            gxbuild3_ledger_decode(_decoded "${_base}")
            string(REGEX REPLACE "[ \t]" "" _decoded "${_decoded}")
            string(FIND "${old_flat_${old}}" "${_decoded}" _at)
            if(_at GREATER -1)
                set(${out} TRUE)
            endif()
        else()
            string(FIND "${old_text_${old}}" "${_base}" _at)
            if(_at GREATER -1)
                set(${out} TRUE)
            endif()
        endif()
    endif()
endmacro()

# (i) every test_ function, static_assert and PIN still in an old file has a row.
foreach(old IN LISTS ledger_olds)
    scan_old("${old}")
    if(NOT old_exists_${old})
        continue()
    endif()
    set(_symbols "${ledger_symbols_${old}}")
    list(TRANSFORM _symbols REPLACE "#.*$" "" OUTPUT_VARIABLE _bases)
    foreach(fn IN LISTS old_functions_${old})
        if(NOT fn IN_LIST _bases)
            problem("${ledger_name_${old}}: ${old} defines ${fn} but no row names it (rule i)")
        endif()
    endforeach()
    foreach(digest IN LISTS old_statics_${old})
        if(NOT "static_assert#${digest}" IN_LIST _symbols)
            problem("${ledger_name_${old}}: ${old} holds static_assert#${digest} but no row names it (rule i)")
        endif()
    endforeach()
    foreach(pin IN LISTS old_pins_${old})
        if(NOT pin IN_LIST _symbols)
            problem("${ledger_name_${old}}: ${old} holds ${pin} but no row names it (rule i)")
        endif()
    endforeach()
endforeach()

# ---- Checks -----------------------------------------------------------------------------------
set(need_sources FALSE)
foreach(id IN LISTS row_ids)
    if(row_status_${id} STREQUAL "ported" AND NOT row_note_${id})
        set(need_sources TRUE)
    endif()
endforeach()
if(need_sources)
    gxbuild3_gtest_scan_sources("${SOURCE_ROOT}/tests")
endif()

foreach(kind ported merged retired static new pending)
    set(count_${kind} 0)
endforeach()
set(claimed "")
foreach(id IN LISTS row_ids)
    set(where "${row_where_${id}} (${id})")
    set(old "${row_old_${id}}")
    set(symbol "${row_symbol_${id}}")
    set(status "${row_status_${id}}")
    set(new_test "${row_new_${id}}")

    if(status STREQUAL "pending")
        math(EXPR count_pending "${count_pending} + 1")
        scan_old("${old}")
        if(NOT old_exists_${old})
            problem("${where}: still pending but ${old} is deleted (rule b)")
        else()
            symbol_present(present "${old}" "${symbol}")
            if(NOT present)
                problem("${where}: still pending but ${symbol} is gone from ${old} (rule b)")
            endif()
        endif()
        continue()
    endif()

    if(status MATCHES "^merged:")
        math(EXPR count_merged "${count_merged} + 1")
    elseif(status MATCHES "^retired:")
        math(EXPR count_retired "${count_retired} + 1")
    elseif(status MATCHES "^static_assert@")
        math(EXPR count_static "${count_static} + 1")
    else()
        math(EXPR count_${status} "${count_${status}} + 1")
    endif()

    # (c) the old code is gone with the port; a '#'-labelled hand row is not checkable alone.
    if((NOT status STREQUAL "new" AND NOT symbol MATCHES "#") OR symbol MATCHES "^static_assert#")
        symbol_present(present "${old}" "${symbol}")
        if(present)
            problem("${where}: ${status} but ${symbol} is still in ${old} (rule c)")
        endif()
    endif()

    if(status STREQUAL "ported" OR status STREQUAL "new")
        # (a) the case is listed and new_test is the entry it runs in.
        gxbuild3_gtest_key(key "${new_test}")
        if(NOT DEFINED case_of_${key})
            # Name the right spelling when the case exists under another entry.
            set(hint "")
            if(new_test MATCHES "^([^.#]+)\\.([^#]+)#(.+)$")
                if(CMAKE_MATCH_3 MATCHES "\\.")
                    set(gtest "${CMAKE_MATCH_1}.${CMAKE_MATCH_3}")
                else()
                    set(gtest "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}")
                endif()
            else()
                set(gtest "${new_test}")
            endif()
            gxbuild3_gtest_key(gkey "${gtest}")
            if(DEFINED spelling_of_${gkey})
                set(hint ", the case runs in ${spelling_of_${gkey}}")
            endif()
            problem("${where}: ${new_test} is not the ctest entry of any listed case${hint} (rule a)")
            continue()
        endif()
        # (f) one claim per case.
        if(DEFINED claim_${key})
            problem("${where}: ${new_test} is also claimed by ${claim_${key}} (rule f)")
        endif()
        set(claim_${key} "${id}")
        # (g) assertion density, unless the row explains itself in a note.
        if(status STREQUAL "ported" AND NOT row_note_${id} AND row_sites_${id} MATCHES "^[0-9]+$")
            gxbuild3_gtest_split("${case_of_${key}}" suite test)
            string(REGEX REPLACE "^.*/" "" suite "${suite}")
            string(REGEX REPLACE "/.*$" "" test "${test}")
            gxbuild3_gtest_key(body "${suite}.${test}")
            math(EXPR floor "(${row_sites_${id}} + 1) / 2")
            if(NOT DEFINED GTEST_SRC_ASSERTS_${body})
                problem("${where}: no TEST body ${suite}.${test} found under tests/<area>/ (rule g)")
            elseif(GTEST_SRC_ASSERTS_${body} LESS floor)
                problem("${where}: ${suite}.${test} has ${GTEST_SRC_ASSERTS_${body}} EXPECT/ASSERT, below ${floor} (old sites ${row_sites_${id}}): port the checks or explain in a note (rule g)")
            endif()
        endif()
    elseif(status MATCHES "^static_assert@(.+):([0-9]+)$")
        # (d) the new home is a static_assert (or PIN_*) line.
        set(file "${CMAKE_MATCH_1}")
        set(at "${CMAKE_MATCH_2}")
        if(NOT EXISTS "${SOURCE_ROOT}/${file}")
            problem("${where}: ${status}: ${file} does not exist (rule d)")
        else()
            gxbuild3_ledger_read_lines("${SOURCE_ROOT}/${file}" target_lines)
            math(EXPR index "${at} - 1")
            list(LENGTH target_lines length)
            if(index LESS 0 OR NOT index LESS length)
                problem("${where}: ${status}: no line ${at} (rule d)")
            else()
                list(GET target_lines ${index} target)
                if(NOT target MATCHES "static_assert\\(|PIN_(SIZE|FIELD)\\(")
                    problem("${where}: ${status} is not a static_assert line (rule d)")
                endif()
            endif()
        endif()
    endif()
endforeach()

# (e) merge targets: a ported/new row or a listed entry.
foreach(id IN LISTS row_ids)
    if(row_status_${id} MATCHES "^merged:(.+)$")
        set(target "${CMAKE_MATCH_1}")
        if(DEFINED row_status_${target})
            if(NOT row_status_${target} MATCHES "^(ported|new)$")
                problem("${row_where_${id}} (${id}): merged into ${target}, which is ${row_status_${target}} (rule e)")
            endif()
        else()
            gxbuild3_gtest_key(key "${target}")
            if(NOT DEFINED entry_${key})
                problem("${row_where_${id}} (${id}): merged into ${target}, which is neither a row id nor a listed entry (rule e)")
            endif()
        endif()
    endif()
endforeach()

# Pins that must stay listable once their rows have moved.
set(wire_moved FALSE)
set(stfs_errors_moved FALSE)
foreach(id IN LISTS row_ids)
    if(NOT row_status_${id} STREQUAL "pending")
        if(id MATCHES "^Wire\\.static_assert\\.")
            set(wire_moved TRUE)
        elseif(id MATCHES "^Stfs\\.error_cases\\.")
            set(stfs_errors_moved TRUE)
        endif()
    endif()
endforeach()
if(wire_moved)
    set(pins "${SOURCE_ROOT}/tests/core/WireLayoutPins.cpp")
    set(count 0)
    if(EXISTS "${pins}")
        file(STRINGS "${pins}" asserts REGEX "static_assert")
        list(LENGTH asserts count)
    endif()
    if(count LESS 46)
        problem("tests/core/WireLayoutPins.cpp holds ${count} static_assert lines, expected at least 46")
    endif()
endif()
if(stfs_errors_moved)
    set(rows 0)
    set(dev_full 0)
    foreach(bin IN LISTS GTEST_BINARIES)
        foreach(case IN LISTS GTEST_${bin}_CASES)
            if(case MATCHES "^Row/StfsErrorCode\\.")
                math(EXPR rows "${rows} + 1")
            elseif(case MATCHES "^NeedsDevFull/StfsErrorCode\\.")
                math(EXPR dev_full "${dev_full} + 1")
            endif()
        endforeach()
    endforeach()
    if(NOT rows EQUAL 32 OR NOT dev_full EQUAL 1)
        problem("StfsErrorCode lists ${rows} Row/ and ${dev_full} NeedsDevFull/ rows, expected 32 and 1")
    endif()
endif()

list(LENGTH row_ids total)
set(summary "ledger: ported ${count_ported}, merged ${count_merged}, retired ${count_retired}, static ${count_static}, new ${count_new}, pending ${count_pending} (${total} rows)")
if(problems)
    foreach(text IN LISTS problems)
        gxbuild3_ledger_decode(text "${text}")
        message("FAIL: ${text}")
    endforeach()
    list(LENGTH problems count)
    message("${summary}")
    message(FATAL_ERROR "coverage ledger: ${count} problem(s)")
endif()
message(STATUS "${summary}")
