cmake_minimum_required(VERSION 3.29)

# GoogleTest listing guard (permanent). Over every binary registered by gxbuild3_add_gtest
# (<build>/tests/gtest-binaries.txt) and the ctest entries of this build tree it fails when:
#
#   1. a binary lists no case;
#   2. a TEST_P row prints its parameter as raw bytes (`-byte object`: no PrintTo, a key leak)
#      or has a numeric row name (no test::RowName);
#   3. a listed case is run by no ctest entry, or by more than one;
#   4. a ctest entry of a gtest binary runs no --gtest_filter, names a case that is not listed,
#      is a wildcard entry that is not one of the binary's BUNDLE entries, or selects no case;
#   5. a TEST_P row is discovered as its own entry outside a PER_ROW instantiation (TABLE RULE);
#   6. a TEST body of a suite bundled without SKIP_BUNDLE calls GTEST_SKIP (a bundle would hide
#      the skip), or any test source captures stdout/stderr or uses a death test;
#   7. a golden binary (gxbuild3_golden_tests) owns a golden with no tests/golden/<name>.txt.
# It prints `entries E, cases C` per binary.
#
# Inputs (-D): GTEST_BINARIES (registry file), CTEST_COMMAND, BUILD_DIR, CONFIG (may be empty),
# TESTS_DIR (the tests/ source directory), GOLDEN_DIR.

foreach(input GTEST_BINARIES CTEST_COMMAND BUILD_DIR TESTS_DIR GOLDEN_DIR)
    if(NOT DEFINED ${input})
        message(FATAL_ERROR "TestListingGuard: ${input} is required")
    endif()
endforeach()
include(${CMAKE_CURRENT_LIST_DIR}/GtestListing.cmake)

set(problems "")
macro(problem text)
    list(APPEND problems "${text}")
endmacro()

gxbuild3_gtest_load("${GTEST_BINARIES}")
if(GTEST_BINARIES STREQUAL "")
    problem("no GoogleTest binary is registered")
endif()

# ---- The ctest entries of this tree: name and --gtest_filter of every gtest-binary command ----
set(config_args "")
if(NOT CONFIG STREQUAL "")
    set(config_args -C "${CONFIG}")
endif()
execute_process(COMMAND "${CTEST_COMMAND}" --test-dir "${BUILD_DIR}" -N -V ${config_args}
    RESULT_VARIABLE result OUTPUT_VARIABLE ctest_out ERROR_VARIABLE ctest_err)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "TestListingGuard: ctest -N failed (${result}): ${ctest_err}")
endif()
gxbuild3_gtest_encode(ctest_lines "${ctest_out}")
set(entry_numbers "")
foreach(line IN LISTS ctest_lines)
    if(line MATCHES "^([0-9]+): Test command: (.*)$")
        set(command_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
    elseif(line MATCHES "^ *Test +#([0-9]+): (.+)$")
        set(name_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
        list(APPEND entry_numbers ${CMAKE_MATCH_1})
    endif()
endforeach()

# gtest filter -> anchored regex (positive and negative halves).
function(filter_regex out patterns)
    set(alternatives "")
    string(REPLACE ":" ";" patterns "${patterns}")
    foreach(pattern IN LISTS patterns)
        string(REGEX REPLACE "([.+()^$|{}])" "\\\\\\1" pattern "${pattern}")
        string(REPLACE "*" ".*" pattern "${pattern}")
        string(REPLACE "?" "." pattern "${pattern}")
        list(APPEND alternatives "${pattern}")
    endforeach()
    list(JOIN alternatives "|" joined)
    set(${out} "^(${joined})$" PARENT_SCOPE)
endfunction()

foreach(bin IN LISTS GTEST_BINARIES)
    set(prefix "${GTEST_${bin}_PREFIX}")
    set(cases "${GTEST_${bin}_CASES}")
    list(LENGTH cases case_count)
    if(case_count EQUAL 0)
        problem("${bin}: --gtest_list_tests lists no case")
    endif()
    foreach(raw IN LISTS GTEST_${bin}_RAW_PARAMS)
        problem("${bin}: a TEST_P parameter prints as raw bytes (declare GX_PRINT_ROW_AS_NAME): ${raw}")
    endforeach()
    foreach(case IN LISTS cases)
        if(case MATCHES "^[^.]*/[^.]*\\.[^/]*/[0-9]+$")
            problem("${bin}: ${case} has a numeric row name (instantiate with test::RowName{})")
        endif()
        gxbuild3_gtest_key(key "${case}")
        set(reach_${key} 0)
    endforeach()

    set(entries 0)
    foreach(n IN LISTS entry_numbers)
        set(command "${command_${n}}")
        set(name "${name_${n}}")
        string(FIND "${command}" "${GTEST_${bin}_PATH} " at)
        if(NOT at EQUAL 0 AND NOT command STREQUAL "${GTEST_${bin}_PATH}")
            continue()
        endif()
        math(EXPR entries "${entries} + 1")
        if(command MATCHES "\"--gtest_filter=([^\"]*)\"")
            set(filter "${CMAKE_MATCH_1}")
        elseif(command MATCHES " --gtest_filter=([^ ]*)")
            set(filter "${CMAKE_MATCH_1}")
        else()
            problem("${name}: runs ${bin} without --gtest_filter")
            continue()
        endif()
        if(NOT filter MATCHES "[*?:-]")
            # A discovered entry: exactly one case.
            gxbuild3_gtest_key(key "${filter}")
            if(NOT DEFINED reach_${key})
                problem("${name}: runs ${filter}, which ${bin} does not list")
                continue()
            endif()
            math(EXPR reach_${key} "${reach_${key}} + 1")
            if(NOT name STREQUAL "${prefix}.${filter}")
                problem("${name}: a discovered entry must be named ${prefix}.${filter}")
            endif()
            gxbuild3_gtest_split("${filter}" suite test)
            if(suite MATCHES "/" AND NOT suite IN_LIST GTEST_${bin}_PER_ROW)
                problem("${name}: TEST_P row discovered on its own: bundle ${suite} or list it under PER_ROW")
            endif()
            continue()
        endif()
        # A wildcard entry: must be one of the binary's bundles and select at least one case.
        string(REGEX REPLACE "^[^.]*\\." "" bundle "${name}")
        if(NOT name STREQUAL "${prefix}.${bundle}" OR NOT bundle IN_LIST GTEST_${bin}_BUNDLES)
            problem("${name}: wildcard entry (${filter}) is not a BUNDLE of ${bin}")
        endif()
        string(FIND "${filter}" "-" dash)
        if(dash GREATER -1)
            string(SUBSTRING "${filter}" 0 ${dash} positive)
            math(EXPR dash "${dash} + 1")
            string(SUBSTRING "${filter}" ${dash} -1 negative)
        else()
            set(positive "${filter}")
            set(negative "")
        endif()
        if(positive STREQUAL "")
            set(positive "*")
        endif()
        filter_regex(positive_regex "${positive}")
        set(negative_regex "")
        if(NOT negative STREQUAL "")
            filter_regex(negative_regex "${negative}")
        endif()
        set(selected 0)
        foreach(case IN LISTS cases)
            if(case MATCHES "${positive_regex}")
                if(negative_regex STREQUAL "" OR NOT case MATCHES "${negative_regex}")
                    gxbuild3_gtest_key(key "${case}")
                    math(EXPR reach_${key} "${reach_${key}} + 1")
                    math(EXPR selected "${selected} + 1")
                endif()
            endif()
        endforeach()
        if(selected EQUAL 0)
            problem("${name}: bundle filter ${filter} selects no case of ${bin}")
        endif()
    endforeach()

    foreach(case IN LISTS cases)
        gxbuild3_gtest_key(key "${case}")
        if(NOT reach_${key} EQUAL 1)
            problem("${bin}: ${case} is run by ${reach_${key}} ctest entries, not exactly one")
        endif()
    endforeach()
    message(STATUS "${bin}: entries ${entries}, cases ${case_count}")
endforeach()

# ---- Sources: skips inside non-SKIP bundles, captured streams and death tests ------------------
gxbuild3_gtest_scan_sources("${TESTS_DIR}")
foreach(bin IN LISTS GTEST_BINARIES)
    foreach(bundle IN LISTS GTEST_${bin}_BUNDLES)
        if(bundle IN_LIST GTEST_${bin}_SKIP_BUNDLES)
            continue()
        endif()
        string(REGEX REPLACE "^.*/" "" suite "${bundle}")
        if(suite IN_LIST GTEST_SRC_SKIPPING_SUITES)
            problem("${GTEST_${bin}_PREFIX}.${bundle}: suite ${suite} can GTEST_SKIP but the bundle is not listed under SKIP_BUNDLE (or move the skipping case out of the bundle)")
        endif()
    endforeach()
endforeach()
foreach(use IN LISTS GTEST_SRC_FORBIDDEN)
    problem("tests/${use}: captured streams and death tests are not allowed (inject a std::ostream&)")
endforeach()

# ---- Golden ownership: every golden a golden binary renders is a tracked file -----------------
if("gxbuild3_golden_tests" IN_LIST GTEST_BINARIES)
    execute_process(COMMAND "${GTEST_gxbuild3_golden_tests_PATH}" --list-goldens
        RESULT_VARIABLE result OUTPUT_VARIABLE owned ERROR_VARIABLE err)
    if(NOT result EQUAL 0)
        problem("gxbuild3_golden_tests --list-goldens failed (${result}): ${err}")
    else()
        string(REGEX MATCHALL "[^\n]+" owned "${owned}")
        foreach(golden IN LISTS owned)
            if(NOT EXISTS "${GOLDEN_DIR}/${golden}.txt")
                problem("gxbuild3_golden_tests owns ${golden}, but ${GOLDEN_DIR}/${golden}.txt does not exist")
            endif()
        endforeach()
    endif()
endif()

if(problems)
    foreach(text IN LISTS problems)
        gxbuild3_gtest_decode(text "${text}")
        message("FAIL: ${text}")
    endforeach()
    list(LENGTH problems count)
    message(FATAL_ERROR "test listing guard: ${count} problem(s)")
endif()
message(STATUS "test listing guard: OK")
